@rootapi = http://localhost:8000/api/v1

###server test 
 GET http://localhost:8000

### Sign up 
POST {{rootapi}}/auth/signup
Content-Type: application/json

{
  "fName":"sagar",
  "lName":"poudel",
  "email" :"sagar@email.com",
  "phone":"0415367939",
  "password":"sagar"
}

### login
POST {{rootapi}}/auth/login
Content-Type: application/json

{
  "email" : "sagar@email.com",
  "password": "sagar"
}


### get all books 

GET {{rootapi}}/book
Content-Type: application/json


### get book by id
GET {{rootapi}}/book/674664c6231d6bfd121d97e9
Authorization: Bearer 
Content-Type: application/json

### Add Book 
POST {{rootapi}}/book/addBook
Authorization: Bearer 
Content-Type: application/json

{
  "title":"new",
  "author":"new",
  "isbn" :"12398848",
  "genre":"horror"

}


### Delete book 
DELETE {{rootapi}}/book/674664c6231d6bfd121d97e9
Authorization: Bearer 

### update Book

PATCH  {{rootapi}}/book/6746d7d1f3c9dc2ea6b1526e
Authorization: Bearer 
Content-Type: application/json

{
  "title":"2nd update"
}

### Borrow book 
POST  {{rootapi}}/borrows
Content-Type: application/json

{
  "userId":"6742f941d4722cb2c7bbeb48",
  "bookId": "6746d7d1f3c9dc2ea6b1526e",
  "borrowDate": "2024-12-04"
}

