@rootapi = http://localhost:8000/api/v1

###server test 
 GET http://localhost:8000

### Sign up 
POST {{rootapi}}/auth/signup
Content-Type: application/json

{
  "fName":"sagar",
  "lName":"poudel",
  "email" :"sagar@email.com",
  "phone":"0415367939",
  "password":"sagar"
}

### login
POST {{rootapi}}/auth/login
Content-Type: application/json

{
  "email" : "sagar@email.com",
  "password": "sagar"
}


### get all books 

GET {{rootapi}}/book
Content-Type: application/json


### get book by id
GET {{rootapi}}/book/674664c6231d6bfd121d97e9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQyZjk0MWQ0NzIyY2IyYzdiYmViNDgiLCJlbWFpbCI6InNhZ2FyQGVtYWlsLmNvbSIsImlhdCI6MTczMzEyODg3MSwiZXhwIjoxNzMzMjE1MjcxfQ.Mwu9jUP8k89iue77wqUh4OmzcGtzEZu34vkU2qTnuHw
Content-Type: application/json

### Add Book 
POST {{rootapi}}/book/addBook
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQyZjk0MWQ0NzIyY2IyYzdiYmViNDgiLCJlbWFpbCI6InNhZ2FyQGVtYWlsLmNvbSIsImlhdCI6MTczMjY5NjAwNSwiZXhwIjoxNzMyNzgyNDA1fQ.8f8Uxzx9JyxQf4Is8hm4GZ3XNftiOZrbMy821wdOxUo
Content-Type: application/json

{
  "title":"new",
  "author":"new",
  "isbn" :"12398848",
  "genre":"horror"

}


### Delete book 
DELETE {{rootapi}}/book/674664c6231d6bfd121d97e9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQyZjk0MWQ0NzIyY2IyYzdiYmViNDgiLCJlbWFpbCI6InNhZ2FyQGVtYWlsLmNvbSIsImlhdCI6MTczMzEyODg3MSwiZXhwIjoxNzMzMjE1MjcxfQ.Mwu9jUP8k89iue77wqUh4OmzcGtzEZu34vkU2qTnuHw
Content-Type: application/json

### update Book

PATCH  {{rootapi}}/book/6746d7d1f3c9dc2ea6b1526e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQyZjk0MWQ0NzIyY2IyYzdiYmViNDgiLCJlbWFpbCI6InNhZ2FyQGVtYWlsLmNvbSIsImlhdCI6MTczMzEyODg3MSwiZXhwIjoxNzMzMjE1MjcxfQ.Mwu9jUP8k89iue77wqUh4OmzcGtzEZu34vkU2qTnuHw
Content-Type: application/json

{
  "title":"2nd update"
}

